# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.DecimalField(decimal_places=2, default=0, help_text='Gasoline iha motor', max_digits=3)),
                ('engine_size', models.DecimalField(decimal_places=0, default=125, help_text='Size of engine ( cc )', max_digits=3)),
                ('model', models.CharField(help_text='Model name', max_length=16)),
                ('photo', models.ImageField(blank=True, help_text='Picture of motor', null=True, upload_to=b'')),
            ],
        ),
    ]
